# Site settings
title: Adventures in Public Media
header-img: "img/WILLPhoto.jpg"
email: jackbrighton@gmail.com
description: "Writings on innovation, community, and technology"
baseurl: ""
url: "http://jackbrighton.github.io"
twitter_username: jackbrighton
github_username:  jackbrighton
facebook_username:  jackbrighton
reading_time:     true
words_per_minute: 200

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
